// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"wire-example/dal"
	"wire-example/handler"
	"wire-example/provider/kmq"
	"wire-example/provider/mysql"
	"wire-example/provider/redis"
	"wire-example/provider/zap"
	"wire-example/router"
	"wire-example/service"
)

// Injectors from wire.go:

func BuildItemRouter() *router.ItemRouter {
	client := redis.RClient()
	syncProducer := kmq.KmqClient()
	sugaredLogger := zap.Logger()
	db := mysql.DBClient()
	base := &dal.Base{
		gdb:    db,
		logger: sugaredLogger,
	}
	itemDal := &dal.ItemDal{
		Base: base,
	}
	itemSvc := &service.ItemSvc{
		Rdb:     client,
		Kmq:     syncProducer,
		Logger:  sugaredLogger,
		Itemdal: itemDal,
	}
	itemHandler := &handler.ItemHandler{
		Itemsvc: itemSvc,
	}
	itemRouter := &router.ItemRouter{
		Ih: itemHandler,
	}
	return itemRouter
}
